### ISSUE TITLE
Pathfinder 10.11 broke mindblade improved critical/mind blade

### ISSUE THREAD

**Issue by nullPointerMV** [shadowchemosh/UltimatePsionics#25]
Hi, Upon updating to the 10.11 PF data files, I get the following error when I load an already-existing Soul Knife with "Mind Blade" selected as the target of Improved Critical

Specific error msg:

Menu-selection 'wMindBlade' on pick 'fImpCrit' no longer exists within data files

Will re-adding the Psionics package resolve this? (i.e. are you doing an overwrite/append of the existing fImpCrit?)

Also have the following addons from you:
CPP 2.24
Ult.Psionics 2.6
SC Gaming Addon 2.11
SC Gestalt 0.6

**Comment by shadowchemosh** [comment]
This was fixed and the new version pushed to everyone with the release of the new Pathfinder 3PP Pack.
