### ISSUE TITLE
Errors regarding `sPrepCount`

### ISSUE THREAD

**Issue by gatesvp** [shadowchemosh/UltimatePsionics#26]
![herolab_psionics_error](https://cloud.githubusercontent.com/assets/319590/5535119/cdab662c-8a29-11e4-91df-b53203ead92b.png)

Getting this basically every time there is a recalculation. Not really sure what either of these fields do, they're not referenced in the `.user` files.

**Comment by shadowchemosh** [comment]
This issue was fixed with the latest version of Pathfinder 10.13.

Moving issue over to the 3PP Pack repository as the UP Repository is going away:
https://github.com/shadowchemosh/HL-Pack-3PP
