### ISSUE TITLE
Power - Natural Healing

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/UltimatePsionics#29]
Errata / Ultimate Psionics changed the augment option on this power from 2pp->3hp to 1pp-3hp

source: http://dreamscarredpress.com/dragonfly/ForumsPro/viewtopic/t=979.html

**Comment by shadowchemosh** [comment]
Moving issue over to the 3PP Pack repository as the UP Repository is going away:
https://github.com/shadowchemosh/HL-Pack-3PP
