### ISSUE TITLE
issues with the latest pathfinder basic pack upgrade (3.5)

### ISSUE THREAD

**Issue by BlazingDuke** [shadowchemosh/UltimatePsionics#30]
After loading the pathfinder basic pack upgrade (3.5) neither Ultimate Psionics nor PoW packages work. I tried uninstalling and reinstalling them and they load fine, but the classes just don't show as available and psionic characters already made won't load right.

**Comment by shadowchemosh** [comment]
Please note the Basic Pack does not contain the 3PP classes.  You need to load the 3PP Pack that is where Ultimate Psionics now lives.

See this thread for details:
http://forums.wolflair.com/showpost.php?p=202420&postcount=5
